name: eye_disease_app
description: Eye Disease and Eye Power Detection App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.6

  # Image picker (gallery / camera)
  image_picker: ^1.0.7

  # HTTP for backend API call
  http: ^1.2.0

  # PDF report generation
  pdf: ^3.10.7
  printing: ^5.12.0

  # Doctor locator (Google Maps)
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
